Resources:
  CdkGroup6CAD1240:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMUserChangePassword
    Metadata:
      aws:cdk:path: CdkPlaygroundStack/CdkGroup/Resource
  testCdkRoleecInstanceAccessToS342755AAD:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - ec2.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      RoleName: testCdkRole_ecInstance_AccessToS3
    Metadata:
      aws:cdk:path: CdkPlaygroundStack/testCdkRole_ecInstance_AccessToS3/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.27.0,@aws-cdk/aws-cloudwatch=0.27.0,@aws-cdk/aws-ec2=0.27.0,@aws-cdk/aws-iam=0.27.0,@aws-cdk/cdk=0.27.0,@aws-cdk/cx-api=0.27.0,@aws-cdk/region-info=0.27.0,jsii-runtime=node.js/v11.13.0
